/* CVS $Id: $ */
package com.epimorphics.plb.vocabs; 
import com.hp.hpl.jena.rdf.model.*;
import java.io.ByteArrayInputStream;
 
/**
 * Vocabulary definitions from doap.rdf 
 * @author Auto-generated by schemagen on 22 Mar 2011 11:23 
 */
public class DOAP {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    private static final String SOURCE = 
           "@prefix dc:      <http://purl.org/dc/elements/1.1/> .        \n"
         + "@prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .        \n"
         + "@prefix foaf:    <http://xmlns.com/foaf/0.1/> .        \n"
         + "@prefix xsd:     <http://www.w3.org/2001/XMLSchema#> .        \n"
         + "@prefix owl:     <http://www.w3.org/2002/07/owl#> .        \n"
         + "@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .        \n"
         + "@prefix vs:      <http://www.w3.org/2003/06/sw-vocab-status/ns#> .        \n"
         + "@prefix doap:    <http://usefulinc.com/ns/doap#> .        \n"
         + "doap:download-page        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"Page web à partir de laquelle on peut télécharger le programme.\"@fr , \"Página web de la cuál se puede bajar el software.\"@es , \"Web page from which the project software can be downloaded.\"@en , \"Web-Seite von der die Projekt-Software heruntergeladen werden kann.\"@de , \"Webová stránka, na které lze stáhnout projektový software.\"@cs , \"このプロジェクトのダウンロードできるウェブページ\"@ja ;        \n"
         + "      rdfs:domain doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"Seite zum Herunterladen\"@de , \"página de descarga\"@es , \"page de téléchargement\"@fr , \"download page\"@en , \"ダウンロードページ\"@ja , \"stránka pro stažení\"@cs .        \n"
         + "doap:screenshots        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"Webová stránka projektu se snímky obrazovky.\"@cs , \"Web-Seite mit Screenshots eines Projektes.\"@de , \"Page web avec des captures d'écran du projet.\"@fr , \"Web page with screenshots of project.\"@en , \"Página web con capturas de pantalla del proyecto.\"@es , \"スクリーンショットのあるウェブページ\"@ja ;        \n"
         + "      rdfs:domain doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"captures d'écran\"@fr , \"snímek obrazovky\"@cs , \"capturas de pantalla\"@es , \"Screenshots\"@de , \"screenshots\"@en , \"スクリーンショット\"@ja .        \n"
         + "doap:browse        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"このリポジトリのウェブのウェブのユーザインタフェース\"@ja , \"Webové rozhraní pro prohlížení úložiště.\"@cs , \"Web browser interface to repository.\"@en , \"Web-Browser Interface für das Repository.\"@de , \"Interface web del repositorio.\"@es , \"Interface web au dépôt.\"@fr ;        \n"
         + "      rdfs:domain doap:Repository ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"navegar\"@es , \"prohlížeč\"@cs , \"ウェブのユーザインタフェース\"@ja , \"browse\"@de , \"browse\"@en , \"visualiser\"@fr .        \n"
         + "doap:module        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"Nom du module d'un dépôt.\"@fr , \"Jméno modulu v úložišti.\"@cs , \"Nombre del módulo de un repositorio.\"@es , \"Module name of a repository.\"@en , \"Modul-Name eines Subversion.\"@de , \"このリポジトリのモジュール名前\"@ja ;        \n"
         + "      rdfs:domain        \n"
         + "              [ a       owl:Class ;        \n"
         + "                owl:unionOf (doap:CVSRepository doap:ArchRepository doap:BKRepository)        \n"
         + "              ] ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"モジュール名前\"@ja , \"módulo\"@es , \"module\"@en , \"module\"@fr , \"Modul\"@de , \"modul\"@cs .        \n"
         + "doap:tester        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"Un tester u otro proveedor de control de calidad.\"@es , \"Tester nebo jiný spoluautor kontrolující kvalitu.\"@cs , \"Un testeur ou un collaborateur au contrôle qualité.\"@fr , \"Ein Tester oder anderer Mitarbeiter der Qualitätskontrolle.\"@de , \"A tester or other quality control contributor.\"@en , \"このプロジェクトのため、試験をする人や品質メンテナー。\"@ja ;        \n"
         + "      rdfs:domain doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"Tester\"@de , \"tester\"@en , \"tester\"@es , \"tester\"@cs , \"試験者\"@ja , \"testeur\"@fr ;        \n"
         + "      rdfs:range foaf:Person .        \n"
         + "doap:GitRepository        \n"
         + "      a       rdfs:Class ;        \n"
         + "      rdfs:comment \"Repositorio Git del código fuente.\"@es , \"Úložiště zdrojových kódů Git.\"@cs , \"Dépôt Git du code source.\"@fr , \"Git source code repository.\"@en , \"ソースコードのGitのリポジトリ\"@ja , \"Git Quellcode-Versionierungssystem.\"@de ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"Dépôt Git\"@fr , \"Git Repository\"@en , \"Úložiště Git\"@cs , \"Git repository\"@de , \"Gitのリポジトリ\"@ja , \"Repositorio Git\"@es ;        \n"
         + "      rdfs:subClassOf doap:Repository .        \n"
         + "doap:bug-database        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"Suivi des bugs pour un projet.\"@fr , \"Bug tracker para un proyecto.\"@es , \"Správa chyb projektu.\"@cs , \"Fehlerdatenbank eines Projektes.\"@de , \"このプロジェクのバグ管理ページ\"@ja , \"Bug tracker for a project.\"@en ;        \n"
         + "      rdfs:domain doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"バグページ\"@ja , \"bug database\"@en , \"Fehlerdatenbank\"@de , \"databáze chyb\"@cs , \"base de datos de bugs\"@es , \"suivi des bugs\"@fr .        \n"
         + "doap:platform        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"Indicator of software platform (non-OS specific), e.g. Java, Firefox, ECMA CLR\"@en , \"このプロジェクトの必要なプラットフォーム（OSに関係ない）。例えば：Java、Firefox、ECMA CLRとか。\"@ja ;        \n"
         + "      rdfs:domain doap:Version , doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"プラットフォーム\"@ja , \"platform\"@en ;        \n"
         + "      rdfs:range rdfs:Literal .        \n"
         + "doap:release        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"Une release (révision) d'un projet.\"@fr , \"Relase (verze) projektu.\"@cs , \"A project release.\"@en , \"Un release (versión) de un proyecto.\"@es , \"このプロジェクトのリリース\"@ja , \"Ein Release (Version) eines Projekts.\"@de ;        \n"
         + "      rdfs:domain doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"リリース\"@ja , \"release\"@en , \"release\"@fr , \"release\"@es , \"release\"@cs , \"Release\"@de ;        \n"
         + "      rdfs:range doap:Version .        \n"
         + "doap:blog        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"このプロジェクトに関するブログのURI\"@ja , \"URI of a blog related to a project\"@en ;        \n"
         + "      rdfs:domain doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"ブログ\"@ja , \"blog\"@en ;        \n"
         + "      rdfs:range rdfs:Resource .        \n"
         + "doap:old-homepage        \n"
         + "      a       rdf:Property , owl:InverseFunctionalProperty ;        \n"
         + "      rdfs:comment \"URL adresa předešlé domovské stránky projektu asociované s právě jedním projektem.\"@cs , \"このプロジェクトの前のホームページ。他のプロジェクトの前のホームページじゃないこと。\"@ja , \"\"\"URL der letzten Projekt-Homepage,        \n"
         + "    verbunden mit genau einem Projekt.\"\"\"@de , \"\"\"URL of a project's past homepage,        \n"
         + "    associated with exactly one project.\"\"\"@en , \"\"\"El URL de la antigua página de un proyecto,        \n"
         + "    asociada con exactamente un proyecto.\"\"\"@es , \"\"\"L'URL d'une ancienne page web d'un        \n"
         + "    projet, associée avec un unique projet.\"\"\"@fr ;        \n"
         + "      rdfs:domain doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"old homepage\"@en , \"ancienne page web\"@fr , \"前のホームページ\"@ja , \"Alte Homepage\"@de , \"página web antigua\"@es , \"stará domovská stránka\"@cs ;        \n"
         + "      rdfs:subPropertyOf foaf:homepage .        \n"
         + "doap:helper        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"Colaborador del proyecto.\"@es , \"Projekt-Mitarbeiter.\"@de , \"Project contributor.\"@en , \"Spoluautor projektu.\"@cs , \"このプロジェクトの貢献者\"@ja , \"Collaborateur au projet.\"@fr ;        \n"
         + "      rdfs:domain doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"helper\"@en , \"collaborateur\"@fr , \"Helfer\"@de , \"colaborador\"@es , \"貢献者\"@ja , \"spoluautor\"@cs ;        \n"
         + "      rdfs:range foaf:Person .        \n"
         + "doap:audience        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"目指したユーザたちの説明\"@ja , \"Description of target user base\"@en ;        \n"
         + "      rdfs:domain doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"audience\"@en , \"目指したユーザ\"@ja ;        \n"
         + "      rdfs:range rdfs:Literal .        \n"
         + "doap:language        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"このプロジェクトの翻訳された言語のISO言語コート\"@ja , \"ISO language code a project has been translated into\"@en ;        \n"
         + "      rdfs:domain doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"language\"@en , \"言語\"@ja ;        \n"
         + "      rdfs:range rdfs:Literal .        \n"
         + "doap:name        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"Der Name von Irgendwas\"@de , \"Jméno něčeho.\"@cs , \"A name of something.\"@en , \"何かの名前\"@ja , \"El nombre de algo.\"@es , \"Le nom de quelque chose.\"@fr ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"name\"@en , \"名前\"@ja , \"nombre\"@es , \"jméno\"@cs , \"Name\"@de , \"nom\"@fr ;        \n"
         + "      rdfs:range rdfs:Literal ;        \n"
         + "      rdfs:subPropertyOf rdfs:label .        \n"
         + "doap:programming-language        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"\"\"Langage de programmation avec lequel un projet est implémenté,        \n"
         + "    ou avec lequel il est prévu de l'utiliser.\"\"\"@fr , \"このプログラミングの実装のプログラミング言語、または目指した言語。\"@ja , \"Lenguaje de programación en el que un proyecto es implementado o con el cuál pretende usarse.\"@es , \"Programming language a project is implemented in or intended for use with.\"@en , \"Programmiersprache in der ein Projekt implementiert ist oder intendiert wird zu benutzen.\"@de , \"Programovací jazyk, ve kterém je projekt implementován nebo pro který je zamýšlen k použití.\"@cs ;        \n"
         + "      rdfs:domain doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"Programmiersprache\"@de , \"langage de programmation\"@fr , \"programovací jazyk\"@cs , \"プログラミング言語\"@ja , \"programming language\"@en , \"lenguaje de programación\"@es ;        \n"
         + "      rdfs:range rdfs:Literal .        \n"
         + "doap:Version        \n"
         + "      a       rdfs:Class ;        \n"
         + "      rdfs:comment \"Versionsinformation eines Projekt Releases.\"@de , \"Informace o uvolněné verzi projektu.\"@cs , \"リリースのバーション情報\"@ja , \"Détails sur une version d'une realease d'un projet.\"@fr , \"Información sobre la versión de un release del proyecto.\"@es , \"Version information of a project release.\"@en ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"Versión\"@es , \"Verze\"@cs , \"Version\"@en , \"Version\"@fr , \"Version\"@de , \"バーション\"@ja .        \n"
         + "doap:BKRepository        \n"
         + "      a       owl:Class , rdfs:Class ;        \n"
         + "      rdfs:comment \"Dépôt BitKeeper du code source.\"@fr , \"Úložiště zdrojových kódů BitKeeper.\"@cs , \"BitKeeper Quellcode-Versionierungssystem.\"@de , \"ソースコードのBitKeeperのリポジトリ\"@ja , \"Repositorio BitKeeper del código fuente.\"@es , \"BitKeeper source code repository.\"@en ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"BitKeeperのリポジトリ\"@ja , \"Dépôt BitKeeper\"@fr , \"Úložiště BitKeeper\"@cs , \"Repositorio BitKeeper\"@es , \"BitKeeper Repository\"@en , \"BitKeeper Repository\"@de ;        \n"
         + "      rdfs:subClassOf doap:Repository .        \n"
         + "doap:documenter        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"Proveedor de documentación para el proyecto.\"@es , \"このプロジェクトのドキュメントの貢献者\"@ja , \"Spoluautor dokumentace projektu.\"@cs , \"Contributor of documentation to the project.\"@en , \"Mitarbeiter an der Dokumentation eines Projektes.\"@de , \"Collaborateur à la documentation du projet.\"@fr ;        \n"
         + "      rdfs:domain doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"rédacteur de l'aide\"@fr , \"documenter\"@en , \"dokumentarista\"@cs , \"escritor de ayuda\"@es , \"文章制作者\"@ja , \"Dokumentator\"@de ;        \n"
         + "      rdfs:range foaf:Person .        \n"
         + "doap:file-release        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"URI adresa stažení asociované s revizí.\"@cs , \"URI of download associated with this release.\"@en ;        \n"
         + "      rdfs:domain doap:Version ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"このリリースのダウンロードできるファイルのURI\"@ja , \"file-release\"@en , \"soubor revize\"@cs , \"ファイル\"@ja .        \n"
         + "doap:Repository        \n"
         + "      a       rdfs:Class ;        \n"
         + "      rdfs:comment \"Úložiště zdrojových kódů.\"@cs , \"Quellcode-Versionierungssystem.\"@de , \"Dépôt du code source.\"@fr , \"Source code repository.\"@en , \"ソースコードのリポジトリ\"@ja , \"Repositorio del código fuente.\"@es ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"リポジトリ\"@ja , \"Dépôt\"@fr , \"Repository\"@en , \"Repository\"@de , \"Úložiště\"@cs , \"Repositorio\"@es .        \n"
         + "doap:category        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"A category of project.\"@en , \"Eine Kategorie eines Projektes.\"@de , \"Una categoría de proyecto.\"@es , \"Une catégorie de projet.\"@fr , \"このプロジェクトの分類。\"@ja , \"Kategorie projektu.\"@cs ;        \n"
         + "      rdfs:domain doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"categoría\"@es , \"kategorie\"@cs , \"Kategorie\"@de , \"catégorie\"@fr , \"category\"@en , \"分類\"@ja .        \n"
         + "doap:repository        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"Úložiště zdrojových kódů.\"@cs , \"Quellcode-Versionierungssystem.\"@de , \"Dépôt du code source.\"@fr , \"このプロジェクトのソースコードのリポジトリ\"@ja , \"Source code repository.\"@en , \"Repositorio del código fuente.\"@es ;        \n"
         + "      rdfs:domain doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"リポジトリ\"@ja , \"dépôt\"@fr , \"repositorio\"@es , \"repository\"@en , \"Repository\"@de , \"úložiště\"@cs ;        \n"
         + "      rdfs:range doap:Repository .        \n"
         + "doap:translator        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"このプロジェクトを翻訳する貢献者\"@ja , \"Spoluautor překladu projektu.\"@cs , \"Proveedor de traducciones al proyecto.\"@es , \"Collaborateur à la traduction du projet.\"@fr , \"Contributor of translations to the project.\"@en , \"Mitarbeiter an den Übersetzungen eines Projektes.\"@de ;        \n"
         + "      rdfs:domain doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"translator\"@en , \"Übersetzer\"@de , \"traductor\"@es , \"翻訳者\"@ja , \"traducteur\"@fr , \"překladatel\"@cs ;        \n"
         + "      rdfs:range foaf:Person .        \n"
         + "doap:service-endpoint        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"ことプロジェクトが提供したサーブスを載せるサイト。\"@ja , \"The URI of a web service endpoint where software as a service may be accessed\"@en ;        \n"
         + "      rdfs:domain doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"サービスサイト\"@ja , \"service endpoint\"@en ;        \n"
         + "      rdfs:range rdfs:Resource .        \n"
         + "doap:vendor        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"提供組織、商業の組織や自由の組織。\"@ja , \"Vendor organization: commercial, free or otherwise\"@en ;        \n"
         + "      rdfs:domain doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"vendor\"@en , \"提供組織\"@ja ;        \n"
         + "      rdfs:range foaf:Organization .        \n"
         + "doap:BazaarBranch        \n"
         + "      a       rdfs:Class ;        \n"
         + "      rdfs:comment \"Bazaar source code branch.\"@en , \"ソースコードのBazzarのリポジトリ\"@ja ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"Bazaar Branch\"@en , \"Bazzarのリポジトリ\"@ja ;        \n"
         + "      rdfs:subClassOf doap:Repository .        \n"
         + "doap:ArchRepository        \n"
         + "      a       owl:Class , rdfs:Class ;        \n"
         + "      rdfs:comment \"GNU Arch Quellcode-Versionierungssystem.\"@de , \"Dépôt GNU Arch du code source.\"@fr , \"GNU Arch source code repository.\"@en , \"Repositorio GNU Arch del código fuente.\"@es , \"ソースコードのGNU Archのリポジトリ\"@ja , \"Úložiště zdrojových kódů GNU Arch.\"@cs ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"GNU Arch repository\"@en , \"GNU Arch repository\"@de , \"Dépôt GNU Arch\"@fr , \"Repositorio GNU Arch\"@es , \"Úložiště GNU Arch\"@cs , \"GNU Archのリポジトリ\"@ja ;        \n"
         + "      rdfs:subClassOf doap:Repository .        \n"
         + "doap:Specification        \n"
         + "      a       rdfs:Class ;        \n"
         + "      rdfs:comment \"あるシステムの詳しく書いた明細書。多分技術的なもの。\"@ja , \"A specification of a system's aspects, technical or otherwise.\"@en ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"明細書じ\"@ja , \"Specification\"@en ;        \n"
         + "      rdfs:subClassOf rdfs:Resource .        \n"
         + "doap:anon-root        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"匿名でアクセスできるパス\"@ja , \"Repository für anonymen Zugriff\"@de , \"Repository for anonymous access.\"@en , \"Repositorio para acceso anónimo.\"@es , \"Dépôt pour accès anonyme.\"@fr , \"Úložiště pro anonymní přístup.\"@cs ;        \n"
         + "      rdfs:domain doap:Repository ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"anonymní kořen\"@cs , \"raíz anónima\"@es , \"anonymous root\"@en , \"racine anonyme\"@fr , \"匿名ルート\"@ja , \"Anonymes Root\"@de ;        \n"
         + "      rdfs:range rdfs:Literal .        \n"
         + "doap:DarcsRepository        \n"
         + "      a       rdfs:Class ;        \n"
         + "      rdfs:comment \"Dépôt darcs du code source.\"@fr , \"ソースコードのdarcsのリポジトリ\"@ja , \"darcs source code repository.\"@en , \"Repositorio darcs del código fuente.\"@es ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"Repositorio darcs\"@es , \"darcsのリポジトリ\"@ja , \"darcs Repository\"@en , \"Dépôt darcs\"@fr ;        \n"
         + "      rdfs:subClassOf doap:Repository .        \n"
         + "doap:Project        \n"
         + "      a       rdfs:Class ;        \n"
         + "      rdfs:comment \"プログラミングのプロジェクト\"@ja , \"Ein Projekt.\"@de , \"Projekt.\"@cs , \"A project.\"@en , \"Un proyecto.\"@es , \"Un projet.\"@fr ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"Project\"@en , \"Proyecto\"@es , \"Prijekt\"@de , \"Projekt\"@cs , \"Projet\"@fr , \"プロジェクト\"@ja ;        \n"
         + "      rdfs:subClassOf <http://xmlns.com/wordnet/1.6/Project> , foaf:Project .        \n"
         + "doap:created        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"Fecha en la que algo fue creado, en formato AAAA-MM-DD. e.g. 2004-04-05\"@es , \"Erstellungsdatum von Irgendwas, angegeben im YYYY-MM-DD Format, z.B. 2004-04-05.\"@de , \"Date à laquelle a été créé quelque chose, au format AAAA-MM-JJ (par ex. 2004-04-05)\"@fr , \"何かが作成された日付、AAAA-MM-JJの型、例えば2004-04-05。\"@ja , \"Datum, kdy bylo něco vytvořeno ve formátu RRRR-MM-DD, např. 2004-04-05\"@cs , \"Date when something was created, in YYYY-MM-DD form. e.g. 2004-04-05\"@en ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"créé\"@fr , \"erstellt\"@de , \"created\"@en , \"作成日付\"@ja , \"vytvořeno\"@cs , \"creado\"@es ;        \n"
         + "      rdfs:range rdfs:Literal .        \n"
         + "doap:SVNRepository        \n"
         + "      a       rdfs:Class ;        \n"
         + "      rdfs:comment \"Dépôt Subversion du code source.\"@fr , \"Úložiště zdrojových kódů Subversion.\"@cs , \"ソースコードのSubversionのリポジトリ\"@ja , \"Subversion Quellcode-Versionierungssystem.\"@de , \"Subversion source code repository.\"@en , \"Repositorio Subversion del código fuente.\"@es ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"Subversionのリポジトリ\"@ja , \"Dépôt Subversion\"@fr , \"Subversion Repository\"@en , \"Subversion Repository\"@de , \"Úložiště Subversion\"@cs , \"Repositorio Subversion\"@es ;        \n"
         + "      rdfs:subClassOf doap:Repository .        \n"
         + "doap:mailing-list        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"Mailing list home page or email address.\"@en , \"メーリングリストのホームページやメールアドレス\"@ja , \"Homepage der Mailing Liste oder E-Mail Adresse.\"@de , \"Page web de la liste de diffusion, ou adresse de courriel.\"@fr , \"Domovská stránka nebo e–mailová adresa e–mailové diskuse.\"@cs , \"Página web de la lista de correo o dirección de correo.\"@es ;        \n"
         + "      rdfs:domain doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"Mailing Liste\"@de , \"メーリングリスト\"@ja , \"e–mailová diskuse\"@cs , \"mailing list\"@en , \"lista de correo\"@es , \"liste de diffusion\"@fr .        \n"
         + "doap:homepage        \n"
         + "      a       rdf:Property , owl:InverseFunctionalProperty ;        \n"
         + "      rdfs:comment \"\"\"URL der Projekt-Homepage,        \n"
         + "    verbunden mit genau einem Projekt.\"\"\"@de , \"URL adresa domovské stránky projektu asociované s právě jedním projektem.\"@cs , \"このプロジェクトのホームページのURL。このホームページは他のプロジェクトのホームページじゃないこと。\"@ja , \"\"\"URL of a project's homepage,        \n"
         + "    associated with exactly one project.\"\"\"@en , \"\"\"El URL de la página de un proyecto,        \n"
         + "    asociada con exactamente un proyecto.\"\"\"@es , \"\"\"L'URL de la page web d'un projet,        \n"
         + "    associée avec un unique projet.\"\"\"@fr ;        \n"
         + "      rdfs:domain doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"domovská stránka\"@cs , \"página web\"@es , \"homepage\"@en , \"ホームページ\"@ja , \"page web\"@fr , \"Homepage\"@de ;        \n"
         + "      rdfs:subPropertyOf foaf:homepage .        \n"
         + "doap:        \n"
         + "      a       owl:Ontology ;        \n"
         + "      dc:creator \"Edd Dumbill\" ;        \n"
         + "      dc:description \"Slovník Description of a Project (DOAP, Popis projektu), popsaný použitím W3C RDF Schema a Web Ontology Language.\"@cs , \"\"\"Le vocabulaire Description Of A Project (DOAP, Description D'Un Projet),        \n"
         + "    décrit en utilisant RDF Schema du W3C et OWL.\"\"\"@fr , \"\"\"El vocabulario Description of a Project (DOAP, Descripción de un Proyecto), descrito usando RDF Schema de W3C        \n"
         + "    y Web Ontology Language.\"\"\"@es , \"プロジェクトの説明の語彙(DOAP)。W3C RDF SchemaとWeb Ontology Languageで作られた。\"@ja , \"Das Vokabular \\\"Description of a Project (DOAP)\\\", beschrieben durch W3C RDF Schema and the Web Ontology Language.\"@de , \"The Description of a Project (DOAP) vocabulary, described using W3C RDF Schema and the Web Ontology Language.\" ;        \n"
         + "      dc:format \"application/rdf+xml\" ;        \n"
         + "      dc:rights \"Copyright © 2004-2009 Edd Dumbill\" ;        \n"
         + "      dc:title \"Description of a Project (DOAP) vocabulary\" ;        \n"
         + "      owl:imports <http://xmlns.com/foaf/0.1/index.rdf> ;        \n"
         + "      foaf:maker        \n"
         + "              [ a       foaf:Person ;        \n"
         + "                foaf:mbox <mailto:edd@usefulinc.com> ;        \n"
         + "                foaf:name \"Edd Dumbill\"        \n"
         + "              ] .        \n"
         + "doap:os        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"Operating system that a project is limited to.  Omit this property if the project is not OS-specific.\"@en , \"Operační systém, na jehož použití je projekt limitován. Vynechejte tuto vlastnost, pokud je projekt nezávislý na operačním systému.\"@cs , \"\"\"Sistema opertivo al cuál está limitado el proyecto.  Omita esta propiedad si el proyecto no es específico        \n"
         + "    de un sistema opertaivo en particular.\"\"\"@es , \"\"\"Système d'exploitation auquel est limité le projet. Omettez cette propriété si le        \n"
         + "    projet n'est pas limité à un système d'exploitation.\"\"\"@fr , \"このプロジェクトの限られたオペレーティングシステム。もし、プロジェクトはどのOSも大丈夫なら、このプロパティを書き落としていい。\"@ja , \"Betriebssystem auf dem das Projekt eingesetzt werden kann. Diese Eigenschaft kann ausgelassen werden, wenn das Projekt nicht BS-spezifisch ist.\"@de ;        \n"
         + "      rdfs:domain doap:Version , doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"operating system\"@en , \"système d'exploitation\"@fr , \"Betriebssystem\"@de , \"operační systém\"@cs , \"オペレーティングシステム\"@ja , \"sistema operativo\"@es ;        \n"
         + "      rdfs:range rdfs:Literal .        \n"
         + "doap:license        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"Die URI einer RDF-Beschreibung einer Lizenz unter der die Software herausgegeben wird.\"@de , \"El URI de una descripción RDF de la licencia bajo la cuál se distribuye el software.\"@es , \"The URI of an RDF description of the license the software is distributed under.\"@en , \"URI adresa RDF popisu licence, pod kterou je software distribuován.\"@cs , \"このプロジェクトの散布ライセンスのRDF説明のURI\"@ja , \"L'URI d'une description RDF de la licence sous laquelle le programme est distribué.\"@fr ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"license\"@en , \"ライセンス\"@ja , \"Lizenz\"@de , \"licencia\"@es , \"licence\"@fr , \"licence\"@cs .        \n"
         + "doap:shortdesc        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"Krátký (8 nebo 9 slov) čistě textový popis projektu.\"@cs , \"Short (8 or 9 words) plain text description of a project.\"@en , \"Descripción corta (8 o 9 palabras) en texto plano de un proyecto.\"@es , \"Texte descriptif concis (8 ou 9 mots) d'un projet.\"@fr , \"Kurzbeschreibung (8 oder 9 Wörter) eines Projects als einfacher Text.\"@de , \"日本語の二十文字ぐらいの説明\"@ja ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"krátký popis\"@cs , \"short description\"@en , \"簡単な説明\"@ja , \"Kurzbeschreibung\"@de , \"descripción corta\"@es , \"description courte\"@fr ;        \n"
         + "      rdfs:range rdfs:Literal .        \n"
         + "doap:implements        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"このプロジェクトが実装したシステムの明細書。標準やAPIや明細書のようなもの。\"@ja , \"A specification that a project implements. Could be a standard, API or legally defined level of conformance.\"@en ;        \n"
         + "      rdfs:domain doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"Implements specification\"@en , \"実装した明細書\"@ja ;        \n"
         + "      rdfs:range doap:Specification .        \n"
         + "doap:maintainer        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"Hauptentwickler eines Projektes, der Projektleiter\"@de , \"Správce projektu, vedoucí projektu.\"@cs , \"このプロジェクトのメンテなー及びリーダ。\"@ja , \"Développeur principal d'un projet, un meneur du projet.\"@fr , \"Maintainer of a project, a project leader.\"@en , \"Desarrollador principal de un proyecto, un líder de proyecto.\"@es ;        \n"
         + "      rdfs:domain doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"Projektverantwortlicher\"@de , \"desarrollador principal\"@es , \"správce\"@cs , \"développeur principal\"@fr , \"メンテナー\"@ja , \"maintainer\"@en ;        \n"
         + "      rdfs:range foaf:Person .        \n"
         + "doap:revision        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"Indentificador de la versión de un release de software.\"@es , \"このリリースのリビジョン識別子\"@ja , \"Versionsidentifikator eines Software-Releases.\"@de , \"Identifiant de révision d'une release du programme.\"@fr , \"Revision identifier of a software release.\"@en , \"Identifikátor zpřístupněné revize softwaru.\"@cs ;        \n"
         + "      rdfs:domain doap:Version ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"révision\"@fr , \"リビジョンコート\"@ja , \"revision\"@en , \"verze\"@cs , \"Version\"@de , \"versión\"@es ;        \n"
         + "      rdfs:range rdfs:Literal .        \n"
         + "doap:download-mirror        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"このプロジェクトのダウンロードミラー\"@ja , \"Miroir de la page de téléchargement du programme.\"@fr , \"Spiegel der Seite von die Projekt-Software heruntergeladen werden kann.\"@de , \"Mirror de la página web de descarga.\"@es , \"Mirror of software download web page.\"@en , \"Zrcadlo stránky pro stažení softwaru.\"@cs ;        \n"
         + "      rdfs:domain doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"zrcadlo stránky pro stažení\"@cs , \"download mirror\"@en , \"Spiegel der Seite zum Herunterladen\"@de , \"miroir pour le téléchargement\"@fr , \"mirror de descarga\"@es , \"ダウンロードミラー\"@ja .        \n"
         + "doap:description        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"Čistě textový, 2 až 4 věty dlouhý popis projektu.\"@cs , \"Descripción en texto plano de un proyecto, de 2 a 4 enunciados de longitud.\"@es , \"プロジェクトの文の説明、2から4までの行数。\"@ja , \"Texte descriptif d'un projet, long de 2 à 4 phrases.\"@fr , \"Plain text description of a project, of 2-4 sentences in length.\"@en , \"Beschreibung eines Projekts als einfacher Text mit der Länge von 2 bis 4 Sätzen.\"@de ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"説明\"@ja , \"popis\"@cs , \"description\"@en , \"description\"@fr , \"descripción\"@es , \"Beschreibung\"@de ;        \n"
         + "      rdfs:range rdfs:Literal .        \n"
         + "doap:location        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"Lokation eines Repositorys.\"@de , \"このリポジトリの場所。\"@ja , \"Emplacement d'un dépôt.\"@fr , \"Location of a repository.\"@en , \"lugar de un repositorio.\"@es , \"Umístění úložiště.\"@cs ;        \n"
         + "      rdfs:domain doap:Repository ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"このリポジトリのURL\"@ja , \"repository location\"@en , \"emplacement du dépôt\"@fr , \"Repository Lokation\"@de , \"umístění úložiště\"@cs , \"lugar del respositorio\"@es .        \n"
         + "doap:developer        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"Developer of software for the project.\"@en , \"プロジェクトのソフトウェアの開発者\"@ja , \"Développeur pour le projet.\"@fr , \"Software-Entwickler für eine Projekt.\"@de , \"Vývojář softwaru projektu.\"@cs , \"Desarrollador de software para el proyecto.\"@es ;        \n"
         + "      rdfs:domain doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"Entwickler\"@de , \"developer\"@en , \"desarrollador\"@es , \"開発者\"@ja , \"développeur\"@fr , \"vývojář\"@cs ;        \n"
         + "      rdfs:range foaf:Person .        \n"
         + "doap:CVSRepository        \n"
         + "      a       owl:Class , rdfs:Class ;        \n"
         + "      rdfs:comment \"CVS source code repository.\"@en , \"Úložiště zdrojových kódů CVS.\"@cs , \"Repositorio CVS del código fuente.\"@es , \"CVS Quellcode-Versionierungssystem.\"@de , \"ソースコードのCVSのリポジトリ\"@ja , \"Dépôt CVS du code source.\"@fr ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"Úložiště CVS\"@cs , \"Dépôt CVS\"@fr , \"Repositorio CVS\"@es , \"CVS Repository\"@en , \"CVS Repository\"@de , \"CVSのリポジトリ\"@ja ;        \n"
         + "      rdfs:subClassOf doap:Repository .        \n"
         + "doap:wiki        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"URL of Wiki for collaborative discussion of project.\"@en , \"このプロジェクトの討論用ウィキ\"@ja , \"L'URL du Wiki pour la discussion collaborative sur le projet.\"@fr , \"URL del Wiki para discusión colaborativa del proyecto.\"@es , \"Wiki-URL für die kollaborative Dikussion eines Projektes.\"@de , \"URL adresa wiki projektu pro společné diskuse.\"@cs ;        \n"
         + "      rdfs:domain doap:Project ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"Wiki\"@de , \"wiki\"@en , \"wiki\"@fr , \"wiki\"@es , \"wiki\"@cs , \"ウィキ\"@ja .        \n"
         + "doap:HgRepository        \n"
         + "      a       rdfs:Class ;        \n"
         + "      rdfs:comment \"Mercurial source code repository.\"@en , \"ソースコードのMercurialのリポジトリ\"@ja ;        \n"
         + "      rdfs:isDefinedBy doap: ;        \n"
         + "      rdfs:label \"Mercurialのリポジトリ\"@ja , \"Mercurial Repository\"@en ;        \n"
         + "      rdfs:subClassOf doap:Repository .        \n"
    ;

    /** Read the ontology definition into the source model */ 
    static { 
        m_model.read( new ByteArrayInputStream( SOURCE.getBytes() ), null, "N3" );
    }

    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://usefulinc.com/ns/doap#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>匿名でアクセスできるパスRepository für anonymen ZugriffRepository for anonymous access.Repositorio 
     *  para acceso anónimo.Dépôt pour accès anonyme.Úložiště pro anonymní přístup.</p>
     */
    public static final Property anon_root = m_model.createProperty( "http://usefulinc.com/ns/doap#anon-root" );
    
    /** <p>目指したユーザたちの説明Description of target user base</p> */
    public static final Property audience = m_model.createProperty( "http://usefulinc.com/ns/doap#audience" );
    
    /** <p>このプロジェクトに関するブログのURIURI of a blog related to a project</p> */
    public static final Property blog = m_model.createProperty( "http://usefulinc.com/ns/doap#blog" );
    
    /** <p>このリポジトリのウェブのウェブのユーザインタフェースWebové rozhraní pro prohlížení úložiště.Web browser 
     *  interface to repository.Web-Browser Interface für das Repository.Interface 
     *  web del repositorio.Interface web au dépôt.</p>
     */
    public static final Property browse = m_model.createProperty( "http://usefulinc.com/ns/doap#browse" );
    
    /** <p>Suivi des bugs pour un projet.Bug tracker para un proyecto.Správa chyb projektu.Fehlerdatenbank 
     *  eines Projektes.このプロジェクのバグ管理ページBug tracker for a project.</p>
     */
    public static final Property bug_database = m_model.createProperty( "http://usefulinc.com/ns/doap#bug-database" );
    
    /** <p>A category of project.Eine Kategorie eines Projektes.Una categoría de proyecto.Une 
     *  catégorie de projet.このプロジェクトの分類。Kategorie projektu.</p>
     */
    public static final Property category = m_model.createProperty( "http://usefulinc.com/ns/doap#category" );
    
    /** <p>Fecha en la que algo fue creado, en formato AAAA-MM-DD. e.g. 2004-04-05Erstellungsdatum 
     *  von Irgendwas, angegeben im YYYY-MM-DD Format, z.B. 2004-04-05.Date à laquelle 
     *  a été créé quelque chose, au format AAAA-MM-JJ (par ex. 2004-04-05)何かが作成された日付、AAAA-MM-JJの型、例えば2004-04-05。Datum, 
     *  kdy bylo něco vytvořeno ve formátu RRRR-MM-DD, např. 2004-04-05Date when something 
     *  was created, in YYYY-MM-DD form. e.g. 2004-04-05</p>
     */
    public static final Property created = m_model.createProperty( "http://usefulinc.com/ns/doap#created" );
    
    /** <p>Čistě textový, 2 až 4 věty dlouhý popis projektu.Descripción en texto plano 
     *  de un proyecto, de 2 a 4 enunciados de longitud.プロジェクトの文の説明、2から4までの行数。Texte 
     *  descriptif d'un projet, long de 2 à 4 phrases.Plain text description of a 
     *  project, of 2-4 sentences in length.Beschreibung eines Projekts als einfacher 
     *  Text mit der Länge von 2 bis 4 Sätzen.</p>
     */
    public static final Property description = m_model.createProperty( "http://usefulinc.com/ns/doap#description" );
    
    /** <p>Developer of software for the project.プロジェクトのソフトウェアの開発者Développeur pour le 
     *  projet.Software-Entwickler für eine Projekt.Vývojář softwaru projektu.Desarrollador 
     *  de software para el proyecto.</p>
     */
    public static final Property developer = m_model.createProperty( "http://usefulinc.com/ns/doap#developer" );
    
    /** <p>Proveedor de documentación para el proyecto.このプロジェクトのドキュメントの貢献者Spoluautor 
     *  dokumentace projektu.Contributor of documentation to the project.Mitarbeiter 
     *  an der Dokumentation eines Projektes.Collaborateur à la documentation du projet.</p>
     */
    public static final Property documenter = m_model.createProperty( "http://usefulinc.com/ns/doap#documenter" );
    
    /** <p>このプロジェクトのダウンロードミラーMiroir de la page de téléchargement du programme.Spiegel 
     *  der Seite von die Projekt-Software heruntergeladen werden kann.Mirror de la 
     *  página web de descarga.Mirror of software download web page.Zrcadlo stránky 
     *  pro stažení softwaru.</p>
     */
    public static final Property download_mirror = m_model.createProperty( "http://usefulinc.com/ns/doap#download-mirror" );
    
    /** <p>Page web à partir de laquelle on peut télécharger le programme.Página web 
     *  de la cuál se puede bajar el software.Web page from which the project software 
     *  can be downloaded.Web-Seite von der die Projekt-Software heruntergeladen werden 
     *  kann.Webová stránka, na které lze stáhnout projektový software.このプロジェクトのダウンロードできるウェブページ</p>
     */
    public static final Property download_page = m_model.createProperty( "http://usefulinc.com/ns/doap#download-page" );
    
    /** <p>URI adresa stažení asociované s revizí.URI of download associated with this 
     *  release.</p>
     */
    public static final Property file_release = m_model.createProperty( "http://usefulinc.com/ns/doap#file-release" );
    
    /** <p>Colaborador del proyecto.Projekt-Mitarbeiter.Project contributor.Spoluautor 
     *  projektu.このプロジェクトの貢献者Collaborateur au projet.</p>
     */
    public static final Property helper = m_model.createProperty( "http://usefulinc.com/ns/doap#helper" );
    
    /** <p>URL der Projekt-Homepage, verbunden mit genau einem Projekt.URL adresa domovské 
     *  stránky projektu asociované s právě jedním projektem.このプロジェクトのホームページのURL。このホームページは他のプロジェクトのホームページじゃないこと。URL 
     *  of a project's homepage, associated with exactly one project.El URL de la 
     *  página de un proyecto, asociada con exactamente un proyecto.L'URL de la page 
     *  web d'un projet, associée avec un unique projet.</p>
     */
    public static final Property homepage = m_model.createProperty( "http://usefulinc.com/ns/doap#homepage" );
    
    /** <p>このプロジェクトが実装したシステムの明細書。標準やAPIや明細書のようなもの。A specification that a project implements. 
     *  Could be a standard, API or legally defined level of conformance.</p>
     */
    public static final Property implements_ = m_model.createProperty( "http://usefulinc.com/ns/doap#implements" );
    
    /** <p>このプロジェクトの翻訳された言語のISO言語コートISO language code a project has been translated into</p> */
    public static final Property language = m_model.createProperty( "http://usefulinc.com/ns/doap#language" );
    
    /** <p>Die URI einer RDF-Beschreibung einer Lizenz unter der die Software herausgegeben 
     *  wird.El URI de una descripción RDF de la licencia bajo la cuál se distribuye 
     *  el software.The URI of an RDF description of the license the software is distributed 
     *  under.URI adresa RDF popisu licence, pod kterou je software distribuován.このプロジェクトの散布ライセンスのRDF説明のURIL'URI 
     *  d'une description RDF de la licence sous laquelle le programme est distribué.</p>
     */
    public static final Property license = m_model.createProperty( "http://usefulinc.com/ns/doap#license" );
    
    /** <p>Lokation eines Repositorys.このリポジトリの場所。Emplacement d'un dépôt.Location of a 
     *  repository.lugar de un repositorio.Umístění úložiště.</p>
     */
    public static final Property location = m_model.createProperty( "http://usefulinc.com/ns/doap#location" );
    
    /** <p>Mailing list home page or email address.メーリングリストのホームページやメールアドレスHomepage der 
     *  Mailing Liste oder E-Mail Adresse.Page web de la liste de diffusion, ou adresse 
     *  de courriel.Domovská stránka nebo e–mailová adresa e–mailové diskuse.Página 
     *  web de la lista de correo o dirección de correo.</p>
     */
    public static final Property mailing_list = m_model.createProperty( "http://usefulinc.com/ns/doap#mailing-list" );
    
    /** <p>Hauptentwickler eines Projektes, der ProjektleiterSprávce projektu, vedoucí 
     *  projektu.このプロジェクトのメンテなー及びリーダ。Développeur principal d'un projet, un meneur 
     *  du projet.Maintainer of a project, a project leader.Desarrollador principal 
     *  de un proyecto, un líder de proyecto.</p>
     */
    public static final Property maintainer = m_model.createProperty( "http://usefulinc.com/ns/doap#maintainer" );
    
    /** <p>Nom du module d'un dépôt.Jméno modulu v úložišti.Nombre del módulo de un repositorio.Module 
     *  name of a repository.Modul-Name eines Subversion.このリポジトリのモジュール名前</p>
     */
    public static final Property module = m_model.createProperty( "http://usefulinc.com/ns/doap#module" );
    
    /** <p>Der Name von IrgendwasJméno něčeho.A name of something.何かの名前El nombre de algo.Le 
     *  nom de quelque chose.</p>
     */
    public static final Property name = m_model.createProperty( "http://usefulinc.com/ns/doap#name" );
    
    /** <p>URL adresa předešlé domovské stránky projektu asociované s právě jedním projektem.このプロジェクトの前のホームページ。他のプロジェクトの前のホームページじゃないこと。URL 
     *  der letzten Projekt-Homepage, verbunden mit genau einem Projekt.URL of a project's 
     *  past homepage, associated with exactly one project.El URL de la antigua página 
     *  de un proyecto, asociada con exactamente un proyecto.L'URL d'une ancienne 
     *  page web d'un projet, associée avec un unique projet.</p>
     */
    public static final Property old_homepage = m_model.createProperty( "http://usefulinc.com/ns/doap#old-homepage" );
    
    /** <p>Operating system that a project is limited to. Omit this property if the project 
     *  is not OS-specific.Operační systém, na jehož použití je projekt limitován. 
     *  Vynechejte tuto vlastnost, pokud je projekt nezávislý na operačním systému.Sistema 
     *  opertivo al cuál está limitado el proyecto. Omita esta propiedad si el proyecto 
     *  no es específico de un sistema opertaivo en particular.Système d'exploitation 
     *  auquel est limité le projet. Omettez cette propriété si le projet n'est pas 
     *  limité à un système d'exploitation.このプロジェクトの限られたオペレーティングシステム。もし、プロジェクトはどのOSも大丈夫なら、このプロパティを書き落としていい。Betriebssystem 
     *  auf dem das Projekt eingesetzt werden kann. Diese Eigenschaft kann ausgelassen 
     *  werden, wenn das Projekt nicht BS-spezifisch ist.</p>
     */
    public static final Property os = m_model.createProperty( "http://usefulinc.com/ns/doap#os" );
    
    /** <p>Indicator of software platform (non-OS specific), e.g. Java, Firefox, ECMA 
     *  CLRこのプロジェクトの必要なプラットフォーム（OSに関係ない）。例えば：Java、Firefox、ECMA CLRとか。</p>
     */
    public static final Property platform = m_model.createProperty( "http://usefulinc.com/ns/doap#platform" );
    
    /** <p>Langage de programmation avec lequel un projet est implémenté, ou avec lequel 
     *  il est prévu de l'utiliser.このプログラミングの実装のプログラミング言語、または目指した言語。Lenguaje de programación 
     *  en el que un proyecto es implementado o con el cuál pretende usarse.Programming 
     *  language a project is implemented in or intended for use with.Programmiersprache 
     *  in der ein Projekt implementiert ist oder intendiert wird zu benutzen.Programovací 
     *  jazyk, ve kterém je projekt implementován nebo pro který je zamýšlen k použití.</p>
     */
    public static final Property programming_language = m_model.createProperty( "http://usefulinc.com/ns/doap#programming-language" );
    
    /** <p>Une release (révision) d'un projet.Relase (verze) projektu.A project release.Un 
     *  release (versión) de un proyecto.このプロジェクトのリリースEin Release (Version) eines 
     *  Projekts.</p>
     */
    public static final Property release = m_model.createProperty( "http://usefulinc.com/ns/doap#release" );
    
    /** <p>Úložiště zdrojových kódů.Quellcode-Versionierungssystem.Dépôt du code source.このプロジェクトのソースコードのリポジトリSource 
     *  code repository.Repositorio del código fuente.</p>
     */
    public static final Property repository = m_model.createProperty( "http://usefulinc.com/ns/doap#repository" );
    
    /** <p>Indentificador de la versión de un release de software.このリリースのリビジョン識別子Versionsidentifikator 
     *  eines Software-Releases.Identifiant de révision d'une release du programme.Revision 
     *  identifier of a software release.Identifikátor zpřístupněné revize softwaru.</p>
     */
    public static final Property revision = m_model.createProperty( "http://usefulinc.com/ns/doap#revision" );
    
    /** <p>Webová stránka projektu se snímky obrazovky.Web-Seite mit Screenshots eines 
     *  Projektes.Page web avec des captures d'écran du projet.Web page with screenshots 
     *  of project.Página web con capturas de pantalla del proyecto.スクリーンショットのあるウェブページ</p>
     */
    public static final Property screenshots = m_model.createProperty( "http://usefulinc.com/ns/doap#screenshots" );
    
    /** <p>ことプロジェクトが提供したサーブスを載せるサイト。The URI of a web service endpoint where software 
     *  as a service may be accessed</p>
     */
    public static final Property service_endpoint = m_model.createProperty( "http://usefulinc.com/ns/doap#service-endpoint" );
    
    /** <p>Krátký (8 nebo 9 slov) čistě textový popis projektu.Short (8 or 9 words) plain 
     *  text description of a project.Descripción corta (8 o 9 palabras) en texto 
     *  plano de un proyecto.Texte descriptif concis (8 ou 9 mots) d'un projet.Kurzbeschreibung 
     *  (8 oder 9 Wörter) eines Projects als einfacher Text.日本語の二十文字ぐらいの説明</p>
     */
    public static final Property shortdesc = m_model.createProperty( "http://usefulinc.com/ns/doap#shortdesc" );
    
    /** <p>Un tester u otro proveedor de control de calidad.Tester nebo jiný spoluautor 
     *  kontrolující kvalitu.Un testeur ou un collaborateur au contrôle qualité.Ein 
     *  Tester oder anderer Mitarbeiter der Qualitätskontrolle.A tester or other quality 
     *  control contributor.このプロジェクトのため、試験をする人や品質メンテナー。</p>
     */
    public static final Property tester = m_model.createProperty( "http://usefulinc.com/ns/doap#tester" );
    
    /** <p>このプロジェクトを翻訳する貢献者Spoluautor překladu projektu.Proveedor de traducciones al 
     *  proyecto.Collaborateur à la traduction du projet.Contributor of translations 
     *  to the project.Mitarbeiter an den Übersetzungen eines Projektes.</p>
     */
    public static final Property translator = m_model.createProperty( "http://usefulinc.com/ns/doap#translator" );
    
    /** <p>提供組織、商業の組織や自由の組織。Vendor organization: commercial, free or otherwise</p> */
    public static final Property vendor = m_model.createProperty( "http://usefulinc.com/ns/doap#vendor" );
    
    /** <p>URL of Wiki for collaborative discussion of project.このプロジェクトの討論用ウィキL'URL du 
     *  Wiki pour la discussion collaborative sur le projet.URL del Wiki para discusión 
     *  colaborativa del proyecto.Wiki-URL für die kollaborative Dikussion eines Projektes.URL 
     *  adresa wiki projektu pro společné diskuse.</p>
     */
    public static final Property wiki = m_model.createProperty( "http://usefulinc.com/ns/doap#wiki" );
    
    /** <p>GNU Arch Quellcode-Versionierungssystem.Dépôt GNU Arch du code source.GNU 
     *  Arch source code repository.Repositorio GNU Arch del código fuente.ソースコードのGNU 
     *  ArchのリポジトリÚložiště zdrojových kódů GNU Arch.</p>
     */
    public static final Resource ArchRepository = m_model.createResource( "http://usefulinc.com/ns/doap#ArchRepository" );
    
    /** <p>Dépôt BitKeeper du code source.Úložiště zdrojových kódů BitKeeper.BitKeeper 
     *  Quellcode-Versionierungssystem.ソースコードのBitKeeperのリポジトリRepositorio BitKeeper 
     *  del código fuente.BitKeeper source code repository.</p>
     */
    public static final Resource BKRepository = m_model.createResource( "http://usefulinc.com/ns/doap#BKRepository" );
    
    /** <p>Bazaar source code branch.ソースコードのBazzarのリポジトリ</p> */
    public static final Resource BazaarBranch = m_model.createResource( "http://usefulinc.com/ns/doap#BazaarBranch" );
    
    /** <p>CVS source code repository.Úložiště zdrojových kódů CVS.Repositorio CVS del 
     *  código fuente.CVS Quellcode-Versionierungssystem.ソースコードのCVSのリポジトリDépôt CVS 
     *  du code source.</p>
     */
    public static final Resource CVSRepository = m_model.createResource( "http://usefulinc.com/ns/doap#CVSRepository" );
    
    /** <p>Dépôt darcs du code source.ソースコードのdarcsのリポジトリdarcs source code repository.Repositorio 
     *  darcs del código fuente.</p>
     */
    public static final Resource DarcsRepository = m_model.createResource( "http://usefulinc.com/ns/doap#DarcsRepository" );
    
    /** <p>Repositorio Git del código fuente.Úložiště zdrojových kódů Git.Dépôt Git du 
     *  code source.Git source code repository.ソースコードのGitのリポジトリGit Quellcode-Versionierungssystem.</p>
     */
    public static final Resource GitRepository = m_model.createResource( "http://usefulinc.com/ns/doap#GitRepository" );
    
    /** <p>Mercurial source code repository.ソースコードのMercurialのリポジトリ</p> */
    public static final Resource HgRepository = m_model.createResource( "http://usefulinc.com/ns/doap#HgRepository" );
    
    /** <p>プログラミングのプロジェクトEin Projekt.Projekt.A project.Un proyecto.Un projet.</p> */
    public static final Resource Project = m_model.createResource( "http://usefulinc.com/ns/doap#Project" );
    
    /** <p>Úložiště zdrojových kódů.Quellcode-Versionierungssystem.Dépôt du code source.Source 
     *  code repository.ソースコードのリポジトリRepositorio del código fuente.</p>
     */
    public static final Resource Repository = m_model.createResource( "http://usefulinc.com/ns/doap#Repository" );
    
    /** <p>Dépôt Subversion du code source.Úložiště zdrojových kódů Subversion.ソースコードのSubversionのリポジトリSubversion 
     *  Quellcode-Versionierungssystem.Subversion source code repository.Repositorio 
     *  Subversion del código fuente.</p>
     */
    public static final Resource SVNRepository = m_model.createResource( "http://usefulinc.com/ns/doap#SVNRepository" );
    
    /** <p>あるシステムの詳しく書いた明細書。多分技術的なもの。A specification of a system's aspects, technical 
     *  or otherwise.</p>
     */
    public static final Resource Specification = m_model.createResource( "http://usefulinc.com/ns/doap#Specification" );
    
    /** <p>Versionsinformation eines Projekt Releases.Informace o uvolněné verzi projektu.リリースのバーション情報Détails 
     *  sur une version d'une realease d'un projet.Información sobre la versión de 
     *  un release del proyecto.Version information of a project release.</p>
     */
    public static final Resource Version = m_model.createResource( "http://usefulinc.com/ns/doap#Version" );
    
}
