/* CVS $Id: $ */
package com.epimorphics.plb.vocabs; 
import com.hp.hpl.jena.rdf.model.*;
import java.io.ByteArrayInputStream;
 
/**
 * Vocabulary definitions from sindice-search.rdf 
 * @author Auto-generated by schemagen on 23 Mar 2011 11:19 
 */
public class Sindice {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    private static final String SOURCE = 
           "@prefix dc:      <http://purl.org/dc/elements/1.1/> .        \n"
         + "@prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .        \n"
         + "@prefix foaf:    <http://xmlns.com/foaf/0.1/> .        \n"
         + "@prefix xsd:     <http://www.w3.org/2001/XMLSchema#> .        \n"
         + "@prefix owl:     <http://www.w3.org/2002/07/owl#> .        \n"
         + "@prefix vann:    <http://purl.org/vocab/vann/> .        \n"
         + "@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .        \n"
         + "<http://sindice.com/vocab/search#Query>        \n"
         + "      a       owl:Class , rdfs:Class ;        \n"
         + "      rdfs:comment \"A search query\" ;        \n"
         + "      rdfs:isDefinedBy <http://vocab.deri.ie/search> ;        \n"
         + "      rdfs:label \"Query\" .        \n"
         + "<http://sindice.com/vocab/search#result>        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"A link from a search query to an individual search result of that query\" ;        \n"
         + "      rdfs:domain rdfs:Resource ;        \n"
         + "      rdfs:isDefinedBy <http://vocab.deri.ie/search> ;        \n"
         + "      rdfs:label \"Result\" ;        \n"
         + "      rdfs:range rdfs:Resource .        \n"
         + "<http://sindice.com/vocab/search#searchTerms>        \n"
         + "      a       rdf:Property , owl:DatatypeProperty ;        \n"
         + "      rdfs:comment \"The search terms used in a search query\" ;        \n"
         + "      rdfs:domain rdfs:Resource ;        \n"
         + "      rdfs:isDefinedBy <http://vocab.deri.ie/search> ;        \n"
         + "      rdfs:label \"Search Terms\" ;        \n"
         + "      rdfs:range rdfs:Literal .        \n"
         + "<http://sindice.com/vocab/search#itemsPerPage>        \n"
         + "      a       rdf:Property , owl:DatatypeProperty ;        \n"
         + "      rdfs:comment \"The number of items found on each page in a paged list of search results\" ;        \n"
         + "      rdfs:domain rdfs:Resource ;        \n"
         + "      rdfs:isDefinedBy <http://vocab.deri.ie/search> ;        \n"
         + "      rdfs:label \"Items per Page\" ;        \n"
         + "      rdfs:range xsd:integer .        \n"
         + "<http://vocab.deri.ie/search#cygri>        \n"
         + "      a       foaf:Person ;        \n"
         + "      foaf:homepage <http://richard.cyganiak.de/> ;        \n"
         + "      foaf:mbox <mailto:richard.cyganiak@deri.org> ;        \n"
         + "      foaf:name \"Richard Cyganiak\" .        \n"
         + "<http://sindice.com/vocab/search#openSearchDescription>        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"A link to an OpenSearch XML description of a search service\" ;        \n"
         + "      rdfs:domain rdfs:Resource ;        \n"
         + "      rdfs:isDefinedBy <http://vocab.deri.ie/search> ;        \n"
         + "      rdfs:label \"OpenSearch Description\" ;        \n"
         + "      rdfs:range rdfs:Resource .        \n"
         + "<http://sindice.com/vocab/search#cache>        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"Link to a cached copy of a search result\" ;        \n"
         + "      rdfs:domain rdfs:Resource ;        \n"
         + "      rdfs:isDefinedBy <http://vocab.deri.ie/search> ;        \n"
         + "      rdfs:label \"Cache\" ;        \n"
         + "      rdfs:range rdfs:Resource .        \n"
         + "<http://sindice.com/vocab/search#first>        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"A link to the first page of results to a search query\" ;        \n"
         + "      rdfs:domain rdfs:Resource ;        \n"
         + "      rdfs:isDefinedBy <http://vocab.deri.ie/search> ;        \n"
         + "      rdfs:label \"First\" ;        \n"
         + "      rdfs:range rdfs:Resource .        \n"
         + "<http://sindice.com/vocab/search#next>        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"A link from one page of a paged search result to the following page\" ;        \n"
         + "      rdfs:domain rdfs:Resource ;        \n"
         + "      rdfs:isDefinedBy <http://vocab.deri.ie/search> ;        \n"
         + "      rdfs:label \"Next\" ;        \n"
         + "      rdfs:range rdfs:Resource .        \n"
         + "<http://vocab.deri.ie/search>        \n"
         + "      a       owl:Ontology ;        \n"
         + "      dc:creator <http://vocab.deri.ie/search#cygri> ;        \n"
         + "      dc:description \"A vocabulary for ranked search results, for use in the Sindice API.\" ;        \n"
         + "      dc:title \"Sindice Search Vocabulary\" ;        \n"
         + "      vann:preferredNamespacePrefix        \n"
         + "              \"search\" ;        \n"
         + "      vann:preferredNamespaceUri        \n"
         + "              \"http://sindice.com/vocab/search#\" .        \n"
         + "<http://sindice.com/vocab/search#Page>        \n"
         + "      a       owl:Class , rdfs:Class ;        \n"
         + "      rdfs:comment \"A page in a paged list of search results\" ;        \n"
         + "      rdfs:isDefinedBy <http://vocab.deri.ie/search> ;        \n"
         + "      rdfs:label \"Page\" .        \n"
         + "<http://vocab.deri.ie/search#Digital%20Enterprise%20Research%20Institute%2C%20NUI%20Galway>        \n"
         + "      a       foaf:Organization ;        \n"
         + "      foaf:homepage <http://www.deri.ie/> ;        \n"
         + "      foaf:member <http://vocab.deri.ie/search#cygri> ;        \n"
         + "      foaf:name \"Digital Enterprise Research Institute, NUI Galway\" .        \n"
         + "<http://sindice.com/vocab/search#page>        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"A link from a paged list of search results to one page within that list\" ;        \n"
         + "      rdfs:domain rdfs:Resource ;        \n"
         + "      rdfs:isDefinedBy <http://vocab.deri.ie/search> ;        \n"
         + "      rdfs:label \"Page\" ;        \n"
         + "      rdfs:range rdfs:Resource .        \n"
         + "<http://sindice.com/vocab/search#link>        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"A link to a resource that was found as a search result\" ;        \n"
         + "      rdfs:domain rdfs:Resource ;        \n"
         + "      rdfs:isDefinedBy <http://vocab.deri.ie/search> ;        \n"
         + "      rdfs:label \"Link\" ;        \n"
         + "      rdfs:range rdfs:Resource .        \n"
         + "<http://sindice.com/vocab/search#startIndex>        \n"
         + "      a       rdf:Property , owl:DatatypeProperty ;        \n"
         + "      rdfs:comment \"The rank (or index) of the first result on a page of search results\" ;        \n"
         + "      rdfs:domain rdfs:Resource ;        \n"
         + "      rdfs:isDefinedBy <http://vocab.deri.ie/search> ;        \n"
         + "      rdfs:label \"Start Index\" ;        \n"
         + "      rdfs:range xsd:integer .        \n"
         + "<http://sindice.com/vocab/search#Result>        \n"
         + "      a       owl:Class , rdfs:Class ;        \n"
         + "      rdfs:comment \"An individual result in a list of ranked search results to a search query\" ;        \n"
         + "      rdfs:isDefinedBy <http://vocab.deri.ie/search> ;        \n"
         + "      rdfs:label \"Result\" .        \n"
         + "<http://sindice.com/vocab/search#rank>        \n"
         + "      a       rdf:Property , owl:DatatypeProperty ;        \n"
         + "      rdfs:comment \"The rank (or index) of an individual search result item within the list of search results\" ;        \n"
         + "      rdfs:domain rdfs:Resource ;        \n"
         + "      rdfs:isDefinedBy <http://vocab.deri.ie/search> ;        \n"
         + "      rdfs:label \"Rank\" ;        \n"
         + "      rdfs:range xsd:integer .        \n"
         + "<http://sindice.com/vocab/search#previous>        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"A link from one page of a paged search result to the preceding page\" ;        \n"
         + "      rdfs:domain rdfs:Resource ;        \n"
         + "      rdfs:isDefinedBy <http://vocab.deri.ie/search> ;        \n"
         + "      rdfs:label \"Previous\" ;        \n"
         + "      rdfs:range rdfs:Resource .        \n"
         + "<http://sindice.com/vocab/search#totalResults>        \n"
         + "      a       rdf:Property , owl:DatatypeProperty ;        \n"
         + "      rdfs:comment \"The total number of results of a search query\" ;        \n"
         + "      rdfs:domain rdfs:Resource ;        \n"
         + "      rdfs:isDefinedBy <http://vocab.deri.ie/search> ;        \n"
         + "      rdfs:label \"Total Results\" ;        \n"
         + "      rdfs:range xsd:integer .        \n"
         + "<http://sindice.com/vocab/search#last>        \n"
         + "      a       rdf:Property ;        \n"
         + "      rdfs:comment \"A link to the last page of results to a search query\" ;        \n"
         + "      rdfs:domain rdfs:Resource ;        \n"
         + "      rdfs:isDefinedBy <http://vocab.deri.ie/search> ;        \n"
         + "      rdfs:label \"Last\" ;        \n"
         + "      rdfs:range rdfs:Resource .        \n"
    ;

    /** Read the ontology definition into the source model */ 
    static { 
        m_model.read( new ByteArrayInputStream( SOURCE.getBytes() ), null, "N3" );
    }

    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://sindice.com/vocab/search#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>Link to a cached copy of a search result</p> */
    public static final Property cache = m_model.createProperty( "http://sindice.com/vocab/search#cache" );
    
    /** <p>A link to the first page of results to a search query</p> */
    public static final Property first = m_model.createProperty( "http://sindice.com/vocab/search#first" );
    
    /** <p>The number of items found on each page in a paged list of search results</p> */
    public static final Property itemsPerPage = m_model.createProperty( "http://sindice.com/vocab/search#itemsPerPage" );
    
    /** <p>A link to the last page of results to a search query</p> */
    public static final Property last = m_model.createProperty( "http://sindice.com/vocab/search#last" );
    
    /** <p>A link to a resource that was found as a search result</p> */
    public static final Property link = m_model.createProperty( "http://sindice.com/vocab/search#link" );
    
    /** <p>A link from one page of a paged search result to the following page</p> */
    public static final Property next = m_model.createProperty( "http://sindice.com/vocab/search#next" );
    
    /** <p>A link to an OpenSearch XML description of a search service</p> */
    public static final Property openSearchDescription = m_model.createProperty( "http://sindice.com/vocab/search#openSearchDescription" );
    
    /** <p>A link from a paged list of search results to one page within that list</p> */
    public static final Property page = m_model.createProperty( "http://sindice.com/vocab/search#page" );
    
    /** <p>A link from one page of a paged search result to the preceding page</p> */
    public static final Property previous = m_model.createProperty( "http://sindice.com/vocab/search#previous" );
    
    /** <p>The rank (or index) of an individual search result item within the list of 
     *  search results</p>
     */
    public static final Property rank = m_model.createProperty( "http://sindice.com/vocab/search#rank" );
    
    /** <p>A link from a search query to an individual search result of that query</p> */
    public static final Property result = m_model.createProperty( "http://sindice.com/vocab/search#result" );
    
    /** <p>The search terms used in a search query</p> */
    public static final Property searchTerms = m_model.createProperty( "http://sindice.com/vocab/search#searchTerms" );
    
    /** <p>The rank (or index) of the first result on a page of search results</p> */
    public static final Property startIndex = m_model.createProperty( "http://sindice.com/vocab/search#startIndex" );
    
    /** <p>The total number of results of a search query</p> */
    public static final Property totalResults = m_model.createProperty( "http://sindice.com/vocab/search#totalResults" );
    
    /** <p>A page in a paged list of search results</p> */
    public static final Resource Page = m_model.createResource( "http://sindice.com/vocab/search#Page" );
    
    /** <p>A search query</p> */
    public static final Resource Query = m_model.createResource( "http://sindice.com/vocab/search#Query" );
    
    /** <p>An individual result in a list of ranked search results to a search query</p> */
    public static final Resource Result = m_model.createResource( "http://sindice.com/vocab/search#Result" );
    
}
